---
# Create an instance on NeCTAR
- name: Create an instance
  openstack.cloud.server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ item.security_groups }}'
    volumes: '{{ item.volumes }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instance

- ansible.builtin.debug:
    msg: "Instance {{ item.openstack.name }} has been created. IP address is {{ item.openstack.public_v4 }}."
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# Add hosts to Ansible in-memory inventory
- name: Add host
  ansible.builtin.add_host:
    name: '{{ item.openstack.public_v4 }}'
    group: all_hosts
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined


# Create a new hosts file in inventory, add and group the instances ip in to the hosts file
- name: Store and group the created hosts to inventory
  template:
    src: record-ansible-hosts.j2
    dest: "./inventory/hosts.ini"
...