---
# Set up the node to enable CouchDB clustering API
# Reference: https://docs.couchdb.org/en/stable/setup/cluster.html
# curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "node_count":"3"}'
- name: Enable the CouchDB cluster setup API on the server
  uri:
    url: http://127.0.0.1:5984/_cluster_setup
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{ 'action':                  'enable_cluster', 
             'bind_address':            '0.0.0.0',
             'username':                '{{ couchdb_user }}', 
             'password':                '{{ couchdb_password }}', 
             'node_count':              '{{ groups['all'] | length }}',
          }"
    headers:
      Content-Type: "application/json"


...


