---
# Create a security group
- name: Create a security group
  openstack.cloud.security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'
  register: os_sg

# Create security group rules
- name: Create security group rules
  openstack.cloud.security_group_rule:
    security_group: '{{ item.security_group }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: present
  loop: '{{ security_group_rules }}'
  register: os_sg_rules
...