---
# Initiate cluster setup via CouchDB Cluster setup API
# Reference: https://docs.couchdb.org/en/3.2.0/setup/cluster.html
# curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "node_count":"3"}'
- name: Initiate cluster setup
  uri:
    url: http://{{ groups['managers'][0] }}:5984/_cluster_setup
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{ 'action':                  'enable_cluster', 
             'bind_address':            '0.0.0.0',
             'username':                '{{ couchdb_user }}', 
             'password':                '{{ couchdb_password }}', 
             'port':                    '5984',
             'remote_node':             '{{ item }}', 
             'node_count':              '{{ groups['all'] | length }}',
             'remote_current_user':     '{{ couchdb_user }}', 
             'remote_current_password': '{{ couchdb_password }}'
          }"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['workers'] }}"

# Add nodes to CouchDB Cluster via the setup API
# Reference: https://docs.couchdb.org/en/3.2.0/setup/cluster.html
# curl -X POST -H "Content-Type: application/json" http://admin:password@<setup-coordination-node>:5984/_cluster_setup -d '{"action": "add_node", "host":"<remote-node-ip>", "port": <remote-node-port>, "username": "admin", "password":"password"}'
- name: Add nodes to cluster
  uri:
    url: http://{{ groups['managers'][0] }}:5984/_cluster_setup
    status_code: [201, 409]
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{ 'action':                  'add_node', 
             'host':                    '{{ item }}',
             'username':                '{{ couchdb_user }}', 
             'password':                '{{ couchdb_password }}', 
             'port':                    '5984'
          }"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['workers'] }}"

# Finish adding nodes to cluster
# Reference: https://docs.couchdb.org/en/3.2.0/setup/cluster.html
# curl -X POST -H "Content-Type: application/json" http://admin:password@<setup-coordination-node>:5984/_cluster_setup -d '{"action": "finish_cluster"}'
- name: Finish cluster
  uri:
    url: http://{{ groups['managers'][0] }}:5984/_cluster_setup
    status_code: [201, 400]
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{'action': 'finish_cluster'}"
    headers:
      Content-Type: "application/json"

- name: Check membership of cluster
  uri:
    url: http://{{ groups['managers'][0] }}:5984/_membership
    status_code: 200
    method: GET
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
  register: membership
  timeout: 30

- name: Inspect cluster membership
  ansible.builtin.debug:
    msg: Check whether all node match cluster nodes {{ membership }}