---
- name: Load Twitter API keys
  include_vars:
    file: ../tweet_harvester/api_keys.yaml
    name: keys

- name: Install required modules for harvester
  ansible.builtin.pip:
    name: ['couchdb', 'textblob', 'tweepy']
    state: latest

- name: Check if harvester directory exist
  stat:
    path: "{{ havester_directory }}"
  register: directory_stats

- name: Create harvester directory
  file:
    path: "{{ havester_directory }}"
    recurse: yes
    state: directory
    mode: 0777
  when: directory_stats.stat.exists == false

- name: Copy harvester files
  copy:
    src: "{{ local_path_to_havester }}"
    dest: "{{ havester_directory }}"
    owner: ubuntu
    group: ubuntu        
    mode: 0777

# Format: python3 stream.py <consumer key> <consumer secret> <access token> <access token secret> <couch db usr> <couch db pwd> <coudh db address>")
- name: Run harvester
  raw: "cd {{ havester_directory }}; python3 stream.py {{ keys['consumer_key'] }} {{ keys['consumer_secret'] }} {{ keys['access_token'] }} {{ keys['access_token_secret']}} {{ couchdb_user }} {{ couchdb_password }} 127.0.0.1 > temp.txt &"
...