---
- hosts: database
  become: yes
  vars_files:
    - host_vars/common.yaml
    - host_vars/couchdb.yaml
  gather_facts: true
  roles: 
    - role: start-couchdb
#    - role: enable-couchdb-cluster

- hosts: managers
  become: yes
  vars_files:
    - host_vars/common.yaml
    - host_vars/couchdb.yaml
  gather_facts: true
  roles: 
    - role: configure-couchdb-cluster
...