---
- hosts: managers
  become: yes
  vars_files:
    - host_vars/common.yaml
    - host_vars/couchdb.yaml
    - host_vars/harvester.yaml
  gather_facts: true
  roles:
    - role: deploy-tweet-harvester
...
