--- 
- hosts: frontend
  become: yes
  vars_files:
    - host_vars/common.yaml
    - host_vars/frontend.yaml
    - host_vars/couchdb.yaml
  gather_facts: true
  roles:
    - role: deploy-frontend
...
