# COMP90024 - Cluster and Cloud Computing - 2022 S1 Assignment 2
#
---
- hosts: localhost
  vars_files:
    - host_vars/common.yaml
    - host_vars/openstack.yaml
  gather_facts: true
  roles:
    - role: check-prelim
    - role: create-volumes
    - role: create-security-groups
    - role: create-instances

- hosts: all_hosts
  become: yes
  vars_files:
    - host_vars/common.yaml
    - host_vars/openstack.yaml
  gather_facts: true
  roles:
    - role: mount-volumes
    - role: install-docker
...
