---
- name: Install Python dependencies
  apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip']
    state: latest
    update_cache: yes

- name: Update pip
  pip:
    name: ['pip']
    state: latest

- name: Install Docker python module
  ansible.builtin.pip:
    name: ['docker']
    state: latest

- name: Install required system packages
  apt:
    name: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'virtualenv', 'lsb-release']
    state: latest
    update_cache: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install docker-ce
  apt: 
    name: docker-ce
    state: latest
    update_cache: yes
